spring:
  application:
    name: tlias-admin

  datasource:
    url: jdbc:mysql://localhost:3306/tlias?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: shenziyan
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
#      最大单个文件大小
      max-file-size: 10MB
#      最大请求大小 包含所有文件和表单数据
      max-request-size: 10MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#    mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: java-web-ai-shen
    region: cn-beijing

#LTAI5t7tKy5xa48MNEhGKvKf
#5hSzvgr4tecY4BuiVbBCWc4Mjavql0
#